#!/usr/bin/env node

'use strict';

const ChromeLauncher = require('chrome-launcher');
const { argv } = require('yargs');
const { resolve } = require('path');
require('dotenv').config();

const VUE_DEVTOOLS_PATH = process.env.VUE_DEVTOOLS_PATH || ''
const EXTENSION_PATH = resolve(__dirname, '..', 'colada-extension', 'dist');
const START_URL = argv.start_url || '';

// get array of default flags, remove unwanted flags
const flags = ChromeLauncher.Launcher.defaultFlags().filter((flag) => {
  if (flag !== '--disable-extensions') {
    return true;
  }
});

// add additional flags
// note: there is a bug where 180 is as red as it will get lol
flags.push(
  '--install-autogenerated-theme=180,0,0',
  `--load-extension=${VUE_DEVTOOLS_PATH},${EXTENSION_PATH}`,
  '--auto-open-devtools-for-tabs',
);

ChromeLauncher.launch({
  ignoreDefaultFlags: true,
  chromeFlags: flags,
  logLevel: 'error',
  startingUrl: START_URL,
}).then((chrome) => {
  console.log('\nstarted new Chrome instance (Use CTRL-C to terminate).');
});
